module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "main-color": "var(--main-color)",
        "Line-Light": "var(--Line-Light)",
        "secondary-color": "var(--secondary-color)",
        "header-bg": "var(--header-bg)",
        "stats-color": "var(--stats-color)",
        "service-card-shadow": "var(--service-card-shadow)",
        "service-card-hover": "var(--service-card-hover)",
        "partner-card-bg": "var(--partner-card-bg)",
        "slider-bg": "var(--slider-bg)",
        "our-aim-overlay-bg": "var(--our-aim-overlay-bg)",
        "support-card-border": "var(--support-card-border)",
        "option-card-hover": "var(--option-card-hover)",
        "radio-bg": "var(--radio-bg)",
        "radio-active-shadow": "var(--radio-active-shadow)",
        "input-border": "var(--input-border)",
        "input-bg": "var(--input-bg)",
        "input-hover-bg": "var(--input-hover-bg)",
        "input-placeholder": "var(--input-placeholder)",
        "solution-hero": "var(--solution-hero)",
        "back-btn-hover": "var(--back-btn-hover)",
        "light-text": "var(--light-text)",
        "slider-btn-border": "var(--slider-btn-border)",
        "slider-border": "var(--slider-border)",
        "selector-border": "var(--selector-border)",
      },
      backgroundImage: {
        "solution-hero-radial-gradient": "var(--solution-hero-radial-gradient)",
        "loader-home-bg-gradient": "var(--loader-home-bg-gradient)",
        "title-bg-gradient-hover": "var(--title-bg-gradient-hover)",
        "hero-radial-gradient": "var(--hero-radial-gradient)",
        "hero-b-radial-gradient": "var(--hero-b-radial-gradient)",
        "footer-bg-gradient": "var(--footer-bg-gradient)",
        "title-bg-gradient": "var(--title-bg-gradient)",
      },
      boxShadow: {
        "service-card-shadow": "var(--service-card-shadow)",
        "option-card-shadow": "var(--option-card-shadow)",
        "button-shadow": "var(--button-shadow)",
        "slider-btn-shadow": "var(--slider-btn-shadow)",
      },
    },
  },
  plugins: [],
};
